# .github/workflows/build.yml
name: Build

on: workflow_dispatch

jobs:
  build-windows:
    name: build x86_64-pc-windows-msvc
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Compile
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-pc-windows-msvc binary
          path: target/release/alloy-installer.exe


  build-linux:
    name: build x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Compile
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu binary
          path: target/release/alloy-installer

