# .github/workflows/check.yml
name: Check

on: [push]

jobs:
  build_and_test:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - run: 
          cargo check
