# .github/workflows/release.yml
name: Release

on:
  release:
    types: [created]

jobs:
  release-windows:
    name: release x86_64-pc-windows-gnu
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Compile
        run: cargo build --release
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/alloy-installer.exe
          asset_name: Installer_${{ github.ref }}_x64_64-pc-windows-gnu
          tag: ${{ github.ref }}

  release-linux:
    name: release x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Compile
        run: cargo build --release
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/alloy-installer
          asset_name: Installer_${{ github.ref }}_x64_64-unknown-linux-gnu
          tag: ${{ github.ref }}
